# Generated by Django 5.0.6 on 2026-03-23 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('stripe', 'Stripe'), ('kaspi', 'Kaspi Pay')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершён'), ('failed', 'Ошибка'), ('refunded', 'Возвращён')], default='pending', max_length=10)),
                ('mock_transaction_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
